-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 23:42:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rah18b
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rah18b` ;

-- -----------------------------------------------------
-- Schema rah18b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rah18b` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `rah18b` ;

-- -----------------------------------------------------
-- Table `rah18b`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rah18b`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rah18b`.`petstore` (
  `pst_id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` CHAR(9) NOT NULL,
  `pst_phone` BIGINT(10) UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rah18b`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rah18b`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rah18b`.`customer` (
  `cus_id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` CHAR(9) NOT NULL,
  `cus_phone` BIGINT(10) UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rah18b`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rah18b`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rah18b`.`pet` (
  `pet_id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT(6) UNSIGNED NOT NULL,
  `cus_id` SMALLINT(6) UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT(3) NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `pst_id_idx` (`pst_id` ASC),
  INDEX `cus_id_idx` (`cus_id` ASC),
  CONSTRAINT `pst_id`
    FOREIGN KEY (`pst_id`)
    REFERENCES `rah18b`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cus_id`
    FOREIGN KEY (`cus_id`)
    REFERENCES `rah18b`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rah18b`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `rah18b`;
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'PetSmart', '1745 W Bethany Home Rd', 'Phoenix', 'AZ', '85015', 6028412507, 'petsmartsupport@petsmart.com', 'www.petsmart.com', 5000000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Petco', '3495 Sports Arena Blvd', 'San Diego ', 'CA', '92110', 6197581731, 'petcosupport@petco.com', 'www.petco.com', 2000000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Woof Gang Bakery', '5054 Dr Phillips Blvd', 'Orlando ', 'FL', '32819', 4072929663, 'woofgangbakerysupport@woofgangbakery.com', 'www.woofgangbakery.com', 1000000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Supplies Plus', '31130 Orchard Lake Rd', 'Farmington Hills', 'MI', '48334', 2489323113, 'petsuppliesplussupport@petsuppliesplus.com', 'www.petsuppliesplus.com', 4000000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Club', '5028 S Ash Ave #101', 'Tempe ', 'AZ', '85282', 8008888914, 'petclubsupport@petclub.com', 'www.petclub.com', 4500000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet SuperMarket', '960 Emerald Bay Rd', 'South Lake Tahoe', 'CA', '96150', 5305443562, 'petsupermarketsupport@petsupermarket.com', 'www.petsupermarket.com', 3500000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Petsense', '15745 N Hayden Rd #G114', 'Scottsdale', 'AZ', '85260', 4805969292, 'petsensesupport@petsense.com', 'www.petsense.com', 2500000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'PetLand', '881 N Bridge St', 'Chillicothe', 'OH', '45601', 7404690018, 'petlandsupport@petland.com', 'www.petland.com', 1250000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'PetLand Discounts', '355 Crooked Hill Rd', 'Brentwood', 'NY', '11717', 6312736363, 'petlanddiscountssupport@petlanddiscounts.com', 'www.petlanddiscounts.com', 4250000, NULL);
INSERT INTO `rah18b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Unleashed by Petco', '308 Washington St', 'San Diego ', 'CA', '92103', 6197250850, 'unleashedbypetcosupport@unleashedbypetco.com', 'www.unleashedbypetco.com', 1300000, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `rah18b`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `rah18b`;
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Rachel', 'Hester', '2621 Conservation Court', 'Phoenix', 'AZ', '85015', 6023746373, 'rachelhester@gmail.com', 132, 500, 'largest sales amount ');
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Lindsey', 'Gallo', '14842 Bonnybridge Dr', 'San Diego', 'CA', '92110', 6197363819, 'lindseygallo@gmail.com', 154, 450, NULL);
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Claudia', 'Berthoin', '220 John Anderson Dr', 'Orlando', 'FL', '32819', 4073746293, 'cberthoin@gmail.com', 15, 315, NULL);
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Vivian', 'Johnson', '4008 Longwood Circle', 'Farmington Hills', 'MI', '32563', 2483748392, 'vj2846@yahoo.com', 100, 250, 'smallest sales amount');
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Jonathan', 'Ryals', '532 Sunny Drive', 'Tempe', 'AZ', '48334', 8004738283, 'jonryals@icloud.com', 12, 386, NULL);
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'AJ', 'Heflin', '746 Tulip Avenue', 'South Lake Tahoe', 'CA', '96150', 5304839283, 'ajheflin@gmail.com', 6, 372, NULL);
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Melanie', 'Shor', '374 Mills Cove Place', 'Scottsdale', 'AZ', '85260', 4805739273, 'mshor274@gmail.com', 3, 284, NULL);
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Chris', 'Gonzalez', '3726 Flower Drive', 'Chillicothe', 'OH', '45601', 7404739475, 'chrisgonz@yahoo.com', 250, 385, NULL);
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Lexi', 'Schatzberg', '4729 Daisy Lane', 'Brentwood', 'NY', '11717', 6314746293, 'lexischatzberg@icloud.com', 300, 510, NULL);
INSERT INTO `rah18b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Allison', 'Ostarly', '3746 Illinois Place', 'San Diego', 'CA', '92103', 6193847364, 'alliostarly6@gmail.com', 10, 475, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `rah18b`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `rah18b`;
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 1, 'Cat', 'F', 200, 250, 2, 'Tortoiseshell', NULL, 'y', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 2, 'Dog', 'F', 100, 300, 3, 'Yellow/orange', '2017-02-15', 'y', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 3, 'Cat', 'F', 90, 235, 5, 'Black/white', '2014-02-15', 'y', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 4, 'Cat', 'M', 105, 225, 7, 'Orange', NULL, 'y', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 5, 'Dog', 'F', 110, 50, 9, 'Black', '2018-02-15', 'n', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 6, 'Dog', 'M', 125, 217, 2, 'White', NULL, 'n', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 7, 'Dog', 'F', 130, 195, 11, 'Gray/wspots', '2020-02-15', 'y', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 8, 'Cat', 'M', 132, 187, 14, 'Black/white', NULL, 'n', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 9, 'Cat', 'M', 133, 173, 3, 'White/orange', NULL, 'y', 'y', NULL);
INSERT INTO `rah18b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 10, 'Cat', 'F', 148, 176, 17, 'Calico', '2007-02-15', 'y', 'y', NULL);

COMMIT;

